/* DESENVOLVER UM PROGRAMA QUE RECEBE A ALTURA E O SEXO (1 MASCULINO E 2 FEMININO) DE  15 PESSOAS. 
 * O PROGRAMA DEVERÁ MOSTRAR NO FINAL 
 *  A MENOR ALTURA DO GRUPO 
 * A MÉDIA DE ALTURA DAS MULHERES 
 * O NÚMERO DE HOMENS 
 * O SEXO DA PESSOA MAIS ALTA
 */



public class exe23 {

     
}
